"""Seed the disposal_guides collection with curated, responsible-handling guidance.

Run from backend/:  python -m seed.seed_disposal_guides
Idempotent: entries are upserted by waste_type.
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.config import settings  # noqa: E402
from app.db.mongodb import connect_db, close_db, ensure_indexes  # noqa: E402

# Curated, deterministic guidance. Never generated by free-form AI so that the
# safety instructions stay accurate and reviewable.
GUIDES = [
    {
        "waste_type": "Battery",
        "hazard_level": "High",
        "instructions": [
            "Never throw batteries in regular household trash or the recycling bin.",
            "Tape the terminals with insulating tape to prevent short-circuiting.",
            "Place them in a dedicated battery collection box at home until drop-off.",
            "Take them to an authorised e-waste/battery collection centre.",
            "For damaged, leaking, or swollen batteries, handle with gloves and contact your municipality's hazardous waste pickup.",
        ],
        "special_collection_required": True,
        "notes": "Common in batteries, remote controls, toys, and e-scooters. Check your city's schedule for doorstep hazardous waste collection.",
    },
    {
        "waste_type": "E-waste",
        "hazard_level": "Medium",
        "instructions": [
            "Do not put electronics in regular trash.",
            "Remove personal data: factory reset phones/computer, remove SIM and memory cards.",
            "Separate big devices from batteries and cables where possible.",
            "Drop them at an authorised e-waste collection point or a producer take-back drop.",
            "If the device still works, consider donating or selling it first.",
        ],
        "special_collection_required": True,
        "notes": "Covers phones, laptops, chargers, wires, and circuit boards.",
    },
    {
        "waste_type": "CFL/LED Bulb",
        "hazard_level": "Medium",
        "instructions": [
            "CFLs and LED bulbs should not go in regular trash because of small amounts of mercury/electronics.",
            "Wrap a broken bulb in a sealed plastic bag to contain glass and vapour.",
            "Store intact bulbs in a sturdy box, away from children.",
            "Hand them to a dedicated bulb collection point or e-waste drop.",
            "Never burn bulbs and never mix them with glass recycling.",
        ],
        "special_collection_required": True,
        "notes": "Includes tube lights, CFLs, and LED bulbs.",
    },
    {
        "waste_type": "Chemical/Paint",
        "hazard_level": "High",
        "instructions": [
            "Never pour chemicals, paints, solvents, or oils down the drain.",
            "Keep the original, clearly labelled containers.",
            "Let leftover latex paint dry out before disposal; contain oil-based paints separately.",
            "Do not mix chemicals together - mixing can cause toxic fumes or fires.",
            "Contact your municipal hazardous waste service for drop-off or pickup dates.",
        ],
        "special_collection_required": True,
        "notes": "Includes paint thinner, engine oil, pesticides, and household cleaning acids.",
    },
    {
        "waste_type": "Medical/Sharps",
        "hazard_level": "High",
        "instructions": [
            "Do not recycle or reuse syringes, needles, or lancets.",
            "Place sharps in a rigid, puncture-proof container (e.g. a thick plastic bottle) immediately after use.",
            "Label the container 'SHARPS - DO NOT RECYCLE'.",
            "Take it to a designated biomedical waste drop or your local clinic/hospital's collection.",
            "Never place sharps in a public recycling bin or regular trash when someone could be accidentally pricked.",
        ],
        "special_collection_required": True,
        "notes": "Includes expired medicines - prefer depositing them at a pharmacy take-back point where available.",
    },
    {
        "waste_type": "Aerosol Can",
        "hazard_level": "High",
        "instructions": [
            "Aerosol cans are pressurised: never puncture, crush, or burn them.",
            "Confirm the can is completely empty by spraying until no more product comes out.",
            "Do not put aerosol cans in regular trash while still pressurised.",
            "Take empty cans to a scrap metal / special waste collection point.",
            "Full or partially full cans are hazardous - keep them away from heat and flames.",
        ],
        "special_collection_required": True,
        "notes": "Includes deodorants, spray paints, and insecticide cans.",
    },
    {
        "waste_type": "General Hazardous",
        "hazard_level": "Low",
        "instructions": [
            "When in doubt, treat the item as hazardous.",
            "Keep it separate from recyclables and organic waste.",
            "Search online or ask your local ward office for the nearest hazardous waste collection point.",
            "Never burn waste items, especially plastics, electronics, or treated wood.",
        ],
        "special_collection_required": True,
        "notes": "Fallback guidance when the AI is unsure about an item's special handling.",
    },
]


async def seed_disposal_guides(db) -> int:
    """Upsert curated safety guidance into an existing database."""
    collection = db["disposal_guides"]

    for guide in GUIDES:
        await collection.replace_one(
            {"waste_type": guide["waste_type"]}, guide, upsert=True
        )
        print(f"  upserted guide for {guide['waste_type']}")

    return await collection.count_documents({})


async def run() -> None:
    db = await connect_db()
    await ensure_indexes()
    count = await seed_disposal_guides(db)
    print(f"Seed complete. disposal_guides collection now has {count} entries.")
    await close_db()


if __name__ == "__main__":
    asyncio.run(run())
